import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/style.css"
import  { LogoutButton } from "./components/LogoutButton";
import AuthGate from "./components/AuthGate";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className = "js">
      <head>
        <link rel="stylesheet" href="/assets/css/style.css" />
        <title>Schedule App</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ fontWeight: 700 }}>Schedule App</div>
          <LogoutButton />
          <AuthGate>{children}</AuthGate>
      </body>
    </html>
  );
}
